#AdminBundle/Resources/config/routing.yml ************************************
#*****************************************************************************

# MyEvent *******************************************************************
admin_myevent:
    resource: "@AdminBundle/Resources/config/routing/myevent.yml"
    prefix:   /myevent
# TypeEvent ******************************************************************
admin_typeevent:
    resource: "@AdminBundle/Resources/config/routing/typeevent.yml"
    prefix:   /type_d_event
# TypeOfEvent ****************************************************************
admin_typeofevent:
    resource: "@AdminBundle/Resources/config/routing/typeofevent.yml"
    prefix:   /Type_d_evenement
# GroupMember ****************************************************************
admin_groupmember:
    resource: "@AdminBundle/Resources/config/routing/groupmember.yml"
    prefix:   /groupe
# Category *******************************************************************
admin_category:
    resource: "@AdminBundle/Resources/config/routing/category.yml"
    prefix:   /category
# Event **********************************************************************
admin_event:
    resource: "@AdminBundle/Resources/config/routing/event.yml"
    prefix:   /event
#*****************************************************************************
# Actuality ******************************************************************
admin_actuality:
    resource: "@AdminBundle/Resources/config/routing/actuality.yml"
    prefix:   /actualite
#*****************************************************************************
# LevelOfAccess **************************************************************
admin_levelofaccess:
    resource: "@AdminBundle/Resources/config/routing/levelofaccess.yml"
    prefix:   /levelofaccess
#*****************************************************************************
# ProjecUserRole *************************************************************
admin_projectuserrole:
    resource: "@AdminBundle/Resources/config/routing/projectuserrole.yml"
    prefix:   /projectuserrole
#*****************************************************************************
# Problematic ****************************************************************
admin_problematic:
    resource: "@AdminBundle/Resources/config/routing/problematic.yml"
    prefix:   /problematique
# TypeOfProblematic **********************************************************
admin_typeofproblematic:
    resource: "@AdminBundle/Resources/config/routing/typeofproblematic.yml"
    prefix:   /type_de_projet
#*****************************************************************************
# Project ********************************************************************
admin_project:
    resource: "@AdminBundle/Resources/config/routing/project.yml"
    prefix:   /projet
#*****************************************************************************
# Article ********************************************************************
admin_article:
    resource: "@AdminBundle/Resources/config/routing/article.yml"
    prefix:   /article
#*****************************************************************************
# HomePage *******************************************************************
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
#*****************************************************************************
#*****************************************************************************


