user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

#app/config/routing.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin


user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:     /user


app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:     /


app:
    resource: '@AppBundle/Controller/'
    type: annotation
