<?php

namespace AdminBundle\Repository;

/**
 * GroupMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
