<?php

namespace AdminBundle\Repository;

/**
 * LevelOfAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelOfAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
