<?php

namespace AdminBundle\Repository;

/**
 * MyEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyEventRepository extends \Doctrine\ORM\EntityRepository
{
}
