<?php

namespace AdminBundle\Repository;

/**
 * ProblematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblematicRepository extends \Doctrine\ORM\EntityRepository
{
}
