<?php

namespace AdminBundle\Repository;

/**
 * ProjectUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUserRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
