<?php

namespace AdminBundle\Repository;

/**
 * TypeOfProblematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfProblematicRepository extends \Doctrine\ORM\EntityRepository
{
}
