<?php

namespace AdminBundle\Repository;

/**
 * TypeOfEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfEventRepository extends \Doctrine\ORM\EntityRepository
{
}
