myevent_index:
    path:     /
    defaults: { _controller: "AdminBundle:MyEvent:index" }
    methods:  GET

myevent_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:MyEvent:show" }
    methods:  GET

myevent_new:
    path:     /new
    defaults: { _controller: "AdminBundle:MyEvent:new" }
    methods:  [GET, POST]

myevent_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:MyEvent:edit" }
    methods:  [GET, POST]

myevent_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:MyEvent:delete" }
    methods:  DELETE
