typeevent_index:
    path:     /
    defaults: { _controller: "AdminBundle:TypeEvent:index" }
    methods:  GET

typeevent_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:TypeEvent:show" }
    methods:  GET

typeevent_new:
    path:     /new
    defaults: { _controller: "AdminBundle:TypeEvent:new" }
    methods:  [GET, POST]

typeevent_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:TypeEvent:edit" }
    methods:  [GET, POST]

typeevent_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:TypeEvent:delete" }
    methods:  DELETE
