#UserBundle/Resources/config/routing.yml

#user_homepage:
#    path:     /user
#    defaults: { _controller: UserBundle:Default:index }


user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }


